# Generated by Django 3.1.6 on 2021-02-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('nomClient', models.CharField(max_length=50)),
                ('telephoneClient', models.CharField(max_length=20)),
                ('mailClient', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='prestataire',
            fields=[
                ('nomPrestataire', models.CharField(max_length=50, unique=True)),
                ('adressePrestataire', models.CharField(max_length=50)),
                ('telephonePrestataire', models.CharField(max_length=20, unique=True)),
                ('mailPrestataire', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='typeActivite',
            fields=[
                ('typeActivite', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='sorties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeActivite', models.CharField(max_length=20)),
                ('nomSortie', models.CharField(max_length=50)),
                ('tarifActivite', models.FloatField()),
                ('rdvActivite', models.CharField(max_length=200)),
                ('thumbnailActivite', models.URLField()),
                ('dateDispo', models.DateField()),
                ('prestataireActivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activites.prestataire')),
            ],
            options={
                'unique_together': {('prestataireActivite', 'nomSortie', 'dateDispo')},
            },
        ),
    ]
