# Generated by Django 3.1.6 on 2021-03-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorties',
            name='typeActivite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activites.typeactivite'),
        ),
    ]
